### ISSUE TITLE
How do you initialize dataset.zip?

### ISSUE THREAD

**Issue by Suchun-sv** [db-Lee/selfsup_dd#3]
Hi authors,

Thanks for your elegant code, they did help me a lot, but I still have some questions that eager to figure out:
(1) How do you initialize `dataset.zip`, I cannot find the description about it in the paper.
(2) Do you initialize your synthetic dataset X_syn by the original dataset? The train.py:47-57 indicates that you use the load dataset as initialization, but the algorithm 1 in the paper (shown below), you mention your initialization which is confusing to me.

<img width="652" alt="image" src="https://github.com/db-Lee/selfsup_dd/assets/35399433/1da09a5d-0e32-411d-a2f3-5bdde14ef815">

Looking for your reply~

**Comment by seanie12** [comment]
Yes, we choose a random subset of the full dataset for initializing the synthetic dataset $X_s$. For $Y_s$, we initialize it with feature representation of $X_s$ with the teacher model. The arxiv is updated with the latest draft, so please refer to the latest version of arxiv.


<img width="721" alt="image" src="https://github.com/db-Lee/selfsup_dd/assets/19561061/7e2a2eac-c1da-466f-bd4f-ab01c0ac389e">

**Comment by Suchun-sv** [comment]
make sense, thanks a lot!
